apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: karyaapp
  name: karyaapp
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8083
  selector:
    io.kompose.service: karyaapp
  type: LoadBalancer
status:
  loadBalancer: {}
