apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: karyaapp
  name: karyaapp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: karyaapp
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.service.type: LoadBalancer
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/karyanet: "true"
        io.kompose.service: karyaapp
    spec:
      containers:
        - env:
            - name: GET_HOSTS_FROM
              value: dns
          image: gcr.io/coral-burner-309611/karyaapp:v1
          name: karyaapp
          ports:
            - containerPort: 8083
          resources: {}
      restartPolicy: Always
status: {}
