apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: go-simpleapp-pipeline
description: CI/CD pipeline for Go app deployment to Cloud Run
serialPipeline:
  stages:
    - targetId: dev
      profiles: []

---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
description: Cloud Run Dev Environment
run:
  location: us-central1
